// <auto-generated />
using System;
using BHMapp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BHMapp.Migrations
{
    [DbContext(typeof(BHMContext))]
    [Migration("20201009091656_BH2020")]
    partial class BH2020
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BHMapp.Models.Bhamc", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AntenatalCare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateMenstruation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpectedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GestationalAge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HospitalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InterviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InterviewerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OthersQ10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OthersQ13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OthersQ15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OthersQ18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OthersQ20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OthersQ22_4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OthersQ3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OthersQ35")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OthersQ36")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OthersQ4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OthersQ56")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OthersQ67")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OthersQ90")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OthersQ92")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostNatalCare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Q1")
                        .HasColumnType("datetime2");

                    b.Property<int>("Q10")
                        .HasColumnType("int");

                    b.Property<bool>("Q100_1_1")
                        .HasColumnType("bit");

                    b.Property<bool>("Q100_2_1")
                        .HasColumnType("bit");

                    b.Property<bool>("Q100_2_2")
                        .HasColumnType("bit");

                    b.Property<bool>("Q100_2_3")
                        .HasColumnType("bit");

                    b.Property<bool>("Q100_3_1")
                        .HasColumnType("bit");

                    b.Property<bool>("Q100_3_2")
                        .HasColumnType("bit");

                    b.Property<bool>("Q100_3_3")
                        .HasColumnType("bit");

                    b.Property<bool>("Q100_3_4")
                        .HasColumnType("bit");

                    b.Property<bool>("Q100_4_1")
                        .HasColumnType("bit");

                    b.Property<bool>("Q100_4_2")
                        .HasColumnType("bit");

                    b.Property<bool>("Q100_4_3")
                        .HasColumnType("bit");

                    b.Property<bool>("Q100_4_4")
                        .HasColumnType("bit");

                    b.Property<bool>("Q100_4_5")
                        .HasColumnType("bit");

                    b.Property<bool>("Q100_5_1")
                        .HasColumnType("bit");

                    b.Property<bool>("Q100_6_1")
                        .HasColumnType("bit");

                    b.Property<bool>("Q101_1")
                        .HasColumnType("bit");

                    b.Property<bool>("Q101_2")
                        .HasColumnType("bit");

                    b.Property<bool>("Q101_3")
                        .HasColumnType("bit");

                    b.Property<long?>("Q102")
                        .HasColumnType("bigint");

                    b.Property<int>("Q103")
                        .HasColumnType("int");

                    b.Property<long?>("Q11")
                        .HasColumnType("bigint");

                    b.Property<bool>("Q12_1")
                        .HasColumnType("bit");

                    b.Property<bool>("Q12_2")
                        .HasColumnType("bit");

                    b.Property<bool>("Q12_3")
                        .HasColumnType("bit");

                    b.Property<bool>("Q12_4")
                        .HasColumnType("bit");

                    b.Property<bool>("Q12_5")
                        .HasColumnType("bit");

                    b.Property<bool>("Q12_6")
                        .HasColumnType("bit");

                    b.Property<bool>("Q12_7")
                        .HasColumnType("bit");

                    b.Property<int>("Q13")
                        .HasColumnType("int");

                    b.Property<long?>("Q14")
                        .HasColumnType("bigint");

                    b.Property<int>("Q15")
                        .HasColumnType("int");

                    b.Property<int>("Q16")
                        .HasColumnType("int");

                    b.Property<int>("Q17")
                        .HasColumnType("int");

                    b.Property<int>("Q18")
                        .HasColumnType("int");

                    b.Property<int>("Q19")
                        .HasColumnType("int");

                    b.Property<long?>("Q2")
                        .HasColumnType("bigint");

                    b.Property<int>("Q20")
                        .HasColumnType("int");

                    b.Property<int>("Q21")
                        .HasColumnType("int");

                    b.Property<bool>("Q22_1")
                        .HasColumnType("bit");

                    b.Property<bool>("Q22_2")
                        .HasColumnType("bit");

                    b.Property<bool>("Q22_3")
                        .HasColumnType("bit");

                    b.Property<bool>("Q22_4")
                        .HasColumnType("bit");

                    b.Property<int>("Q23")
                        .HasColumnType("int");

                    b.Property<long>("Q24")
                        .HasColumnType("bigint");

                    b.Property<int>("Q25")
                        .HasColumnType("int");

                    b.Property<long?>("Q26")
                        .HasColumnType("bigint");

                    b.Property<int>("Q27")
                        .HasColumnType("int");

                    b.Property<int>("Q28")
                        .HasColumnType("int");

                    b.Property<long?>("Q29")
                        .HasColumnType("bigint");

                    b.Property<int>("Q3")
                        .HasColumnType("int");

                    b.Property<long?>("Q30")
                        .HasColumnType("bigint");

                    b.Property<int>("Q31")
                        .HasColumnType("int");

                    b.Property<int>("Q32")
                        .HasColumnType("int");

                    b.Property<long?>("Q32_1")
                        .HasColumnType("bigint");

                    b.Property<int>("Q33")
                        .HasColumnType("int");

                    b.Property<int>("Q34")
                        .HasColumnType("int");

                    b.Property<int>("Q35")
                        .HasColumnType("int");

                    b.Property<int>("Q36")
                        .HasColumnType("int");

                    b.Property<string>("Q37")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Q38")
                        .HasColumnType("bigint");

                    b.Property<int>("Q39")
                        .HasColumnType("int");

                    b.Property<int>("Q4")
                        .HasColumnType("int");

                    b.Property<long?>("Q40")
                        .HasColumnType("bigint");

                    b.Property<long?>("Q41")
                        .HasColumnType("bigint");

                    b.Property<int>("Q42")
                        .HasColumnType("int");

                    b.Property<bool>("Q43_1")
                        .HasColumnType("bit");

                    b.Property<bool>("Q43_2")
                        .HasColumnType("bit");

                    b.Property<bool>("Q43_3")
                        .HasColumnType("bit");

                    b.Property<bool>("Q43_4")
                        .HasColumnType("bit");

                    b.Property<bool>("Q43_5")
                        .HasColumnType("bit");

                    b.Property<bool>("Q43_6")
                        .HasColumnType("bit");

                    b.Property<int>("Q44")
                        .HasColumnType("int");

                    b.Property<int>("Q45")
                        .HasColumnType("int");

                    b.Property<int>("Q46")
                        .HasColumnType("int");

                    b.Property<int>("Q47")
                        .HasColumnType("int");

                    b.Property<long?>("Q48")
                        .HasColumnType("bigint");

                    b.Property<int>("Q49")
                        .HasColumnType("int");

                    b.Property<int>("Q5")
                        .HasColumnType("int");

                    b.Property<string>("Q50")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Q51")
                        .HasColumnType("bigint");

                    b.Property<string>("Q52")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Q53")
                        .HasColumnType("int");

                    b.Property<int>("Q54")
                        .HasColumnType("int");

                    b.Property<DateTime>("Q54_1")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Q54_2")
                        .HasColumnType("bit");

                    b.Property<string>("Q54_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Q55")
                        .HasColumnType("int");

                    b.Property<int>("Q56")
                        .HasColumnType("int");

                    b.Property<bool>("Q56_1")
                        .HasColumnType("bit");

                    b.Property<bool>("Q56_2")
                        .HasColumnType("bit");

                    b.Property<bool>("Q56_3")
                        .HasColumnType("bit");

                    b.Property<bool>("Q56_4")
                        .HasColumnType("bit");

                    b.Property<bool>("Q56_5")
                        .HasColumnType("bit");

                    b.Property<bool>("Q58_1")
                        .HasColumnType("bit");

                    b.Property<bool>("Q58_2")
                        .HasColumnType("bit");

                    b.Property<bool>("Q58_3")
                        .HasColumnType("bit");

                    b.Property<bool>("Q58_4")
                        .HasColumnType("bit");

                    b.Property<bool>("Q59_1")
                        .HasColumnType("bit");

                    b.Property<bool>("Q59_2")
                        .HasColumnType("bit");

                    b.Property<bool>("Q59_3")
                        .HasColumnType("bit");

                    b.Property<bool>("Q59_4")
                        .HasColumnType("bit");

                    b.Property<bool>("Q59_5")
                        .HasColumnType("bit");

                    b.Property<bool>("Q59_6")
                        .HasColumnType("bit");

                    b.Property<int>("Q6")
                        .HasColumnType("int");

                    b.Property<int>("Q60")
                        .HasColumnType("int");

                    b.Property<DateTime>("Q60_1")
                        .HasColumnType("datetime2");

                    b.Property<string>("Q60_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Q60_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Q61_1")
                        .HasColumnType("bit");

                    b.Property<bool>("Q61_2")
                        .HasColumnType("bit");

                    b.Property<bool>("Q61_3")
                        .HasColumnType("bit");

                    b.Property<bool>("Q61_4")
                        .HasColumnType("bit");

                    b.Property<bool>("Q61_5")
                        .HasColumnType("bit");

                    b.Property<bool>("Q61_6")
                        .HasColumnType("bit");

                    b.Property<int>("Q62")
                        .HasColumnType("int");

                    b.Property<string>("Q63")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Q64_1")
                        .HasColumnType("bit");

                    b.Property<bool>("Q64_2")
                        .HasColumnType("bit");

                    b.Property<bool>("Q64_3")
                        .HasColumnType("bit");

                    b.Property<bool>("Q64_4")
                        .HasColumnType("bit");

                    b.Property<bool>("Q64_5")
                        .HasColumnType("bit");

                    b.Property<int>("Q65")
                        .HasColumnType("int");

                    b.Property<long?>("Q65_1")
                        .HasColumnType("bigint");

                    b.Property<int>("Q66")
                        .HasColumnType("int");

                    b.Property<int>("Q67")
                        .HasColumnType("int");

                    b.Property<int>("Q68")
                        .HasColumnType("int");

                    b.Property<int>("Q68Yes")
                        .HasColumnType("int");

                    b.Property<int>("Q69")
                        .HasColumnType("int");

                    b.Property<long?>("Q7")
                        .HasColumnType("bigint");

                    b.Property<int>("Q70")
                        .HasColumnType("int");

                    b.Property<int>("Q71")
                        .HasColumnType("int");

                    b.Property<long?>("Q71_1")
                        .HasColumnType("bigint");

                    b.Property<int>("Q72")
                        .HasColumnType("int");

                    b.Property<int>("Q73")
                        .HasColumnType("int");

                    b.Property<int>("Q74")
                        .HasColumnType("int");

                    b.Property<int>("Q75")
                        .HasColumnType("int");

                    b.Property<int>("Q76")
                        .HasColumnType("int");

                    b.Property<int>("Q77")
                        .HasColumnType("int");

                    b.Property<int>("Q78")
                        .HasColumnType("int");

                    b.Property<string>("Q79")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Q8")
                        .HasColumnType("int");

                    b.Property<int>("Q80")
                        .HasColumnType("int");

                    b.Property<bool>("Q81_1")
                        .HasColumnType("bit");

                    b.Property<bool>("Q81_2")
                        .HasColumnType("bit");

                    b.Property<bool>("Q81_3")
                        .HasColumnType("bit");

                    b.Property<bool>("Q81_4")
                        .HasColumnType("bit");

                    b.Property<bool>("Q81_5")
                        .HasColumnType("bit");

                    b.Property<bool>("Q81_6")
                        .HasColumnType("bit");

                    b.Property<bool>("Q82_1")
                        .HasColumnType("bit");

                    b.Property<bool>("Q82_2")
                        .HasColumnType("bit");

                    b.Property<bool>("Q82_3")
                        .HasColumnType("bit");

                    b.Property<bool>("Q82_4")
                        .HasColumnType("bit");

                    b.Property<bool>("Q82_5")
                        .HasColumnType("bit");

                    b.Property<int>("Q83")
                        .HasColumnType("int");

                    b.Property<int>("Q84")
                        .HasColumnType("int");

                    b.Property<int>("Q85")
                        .HasColumnType("int");

                    b.Property<long?>("Q85_1")
                        .HasColumnType("bigint");

                    b.Property<int>("Q86")
                        .HasColumnType("int");

                    b.Property<long?>("Q86_1")
                        .HasColumnType("bigint");

                    b.Property<int>("Q87")
                        .HasColumnType("int");

                    b.Property<long?>("Q87_1")
                        .HasColumnType("bigint");

                    b.Property<int>("Q88")
                        .HasColumnType("int");

                    b.Property<int>("Q9")
                        .HasColumnType("int");

                    b.Property<int>("Q90")
                        .HasColumnType("int");

                    b.Property<int>("Q91")
                        .HasColumnType("int");

                    b.Property<int>("Q92")
                        .HasColumnType("int");

                    b.Property<int>("Q93")
                        .HasColumnType("int");

                    b.Property<int>("Q94")
                        .HasColumnType("int");

                    b.Property<int>("Q95")
                        .HasColumnType("int");

                    b.Property<long?>("Q96")
                        .HasColumnType("bigint");

                    b.Property<string>("Q97")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Q98_1")
                        .HasColumnType("bit");

                    b.Property<bool>("Q98_2")
                        .HasColumnType("bit");

                    b.Property<bool>("Q98_3")
                        .HasColumnType("bit");

                    b.Property<bool>("Q98_4")
                        .HasColumnType("bit");

                    b.Property<bool>("Q98_5")
                        .HasColumnType("bit");

                    b.Property<bool>("Q98_6")
                        .HasColumnType("bit");

                    b.Property<bool>("Q99_1")
                        .HasColumnType("bit");

                    b.Property<bool>("Q99_2")
                        .HasColumnType("bit");

                    b.Property<bool>("Q99_3")
                        .HasColumnType("bit");

                    b.Property<bool>("Q99_4")
                        .HasColumnType("bit");

                    b.Property<bool>("Q99_5")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionnaireNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Bhamc");
                });
#pragma warning restore 612, 618
        }
    }
}
