// <auto-generated />
using System;
using BHMapp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BHMapp.Migrations
{
    [DbContext(typeof(BHMContext))]
    partial class BHMContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("BHMapp.Models.Bhamc", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AntenatalCare")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateMenstruation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpectedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GestationalAge")
                        .HasColumnType("TEXT");

                    b.Property<string>("HospitalName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InterviewDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InterviewerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ10")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ13")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ15")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ18")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ20")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ22_4")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ3")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ35")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ36")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ4")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ56")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ67")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ70_4")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ90")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ92")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostNatalCare")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Q1")
                        .HasColumnType("TEXT");

                    b.Property<int>("Q10")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q100_1_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q100_2_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q100_2_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q100_2_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q100_3_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q100_3_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q100_3_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q100_3_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q100_4_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q100_4_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q100_4_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q100_4_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q100_4_5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q100_5_1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q100_6_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q101_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q101_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q101_3")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q102")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q103")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q11")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q12_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q12_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q12_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q12_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q12_5")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q12_6")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q12_7")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q13")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q14")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q15")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q16")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q17")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q18")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q19")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q20")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q21")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q22_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q22_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q22_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q22_4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q23")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Q24")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q25")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q26")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q27")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q28")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q29")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q3")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q30")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q31")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q32")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q32_1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q33")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q34")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q35")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q36")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q37")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("Q38")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q39")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q4")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q40")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q41")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q42")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q43_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q43_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q43_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q43_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q43_5")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q43_6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q44")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q45")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q46")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q47")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q48")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q49")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q5")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q50")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("Q51")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q52")
                        .HasColumnType("TEXT");

                    b.Property<int>("Q53")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q54")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Q54_1")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Q54_2")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q54_3")
                        .HasColumnType("TEXT");

                    b.Property<int>("Q55")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q56")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q56_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q56_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q56_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q56_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q56_5")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q58_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q58_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q58_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q58_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q59_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q59_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q59_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q59_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q59_5")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q59_6")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q60")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Q60_1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q60_2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q60_3")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Q61_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q61_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q61_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q61_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q61_5")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q61_6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q62")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q63")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Q64_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q64_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q64_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q64_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q64_5")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q65")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q66")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q67")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q68")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q68Yes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q69")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q7")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q70_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q70_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q70_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q70_4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q71")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q71_1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q72")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q73")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q74")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q75")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q76")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q77")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q78")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q79")
                        .HasColumnType("TEXT");

                    b.Property<int>("Q8")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q80")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q81_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q81_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q81_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q81_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q81_5")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q81_6")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q82_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q82_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q82_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q82_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q82_5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q83")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q84")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q85")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q86")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q87")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q88")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q89")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q9")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q90")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q91")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q92")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q93")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q94")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q95")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q96")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q97")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q98_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q98_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q98_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q98_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q98_5")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q98_6")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q99_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q99_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q99_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q99_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q99_5")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionnaireNo")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Bhamc");
                });
#pragma warning restore 612, 618
        }
    }
}
